### ISSUE TITLE
failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory

### ISSUE THREAD

**Issue by 25zs25** [esahin99/FishEye-VAST-Challenge-2024-Mini-Challenge-2#1]
missing ./fe 
 
 docker-compose build
2024/11/24 15:59:12 http2: server: error reading preface from client //./pipe/dockerDesktopLinuxEngine: file has already been closed
[+] Building 0.1s (3/3) FINISHED                                                                                                                                                    docker:desktop-linux
 => [djangoapp internal] load build definition from Dockerfile                                                                                                                                      0.0s
 => => transferring dockerfile: 887B                                                                                                                                                                0.0s
 => [frontend internal] load build definition from Dockerfile                                                                                                                                       0.0s
 => => transferring dockerfile: 2B                                                                                                                                                                  0.0s 
 => CANCELED [djangoapp internal] load metadata for docker.io/library/python:3.9                                                                                                                    0.0s 
failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory

please help me ,thanks

**Comment by esahin99** [comment]
Hi sduzs,

I just realized I couldn't upload the fe file because of its size. So, I uploaded the fe file as a zip file (you can see the file named fe.zip). Once you download the repository, please expand the zip and retry to run the code again.

Regards

**Comment by 25zs25** [comment]
Thank you for your response. We don't have the tables in the public schema when using PostgreSQL. Could you please upload them? I would greatly appreciate it.

**Comment by 25zs25** [comment]
Dear esahin99:
When I run fe :

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. 

I'm not sure if the occurrence of this error is due to the backend not returning a response, and I have already ruled out reasons such as a mismatch in the versions of 'react' and 'react-dom'. Below is the output from the backend (be) server:

[25/Nov/2024 11:21:14] "GET /main/transponder-pings/?start_date=2035-02-01&end_date=2035-03-01 HTTP/1.1" 500 145
[25/Nov/2024 11:21:14] "GET /main/trend-line/ HTTP/1.1" 500 145
[25/Nov/2024 11:21:14] "GET /main/trend-data/ HTTP/1.1" 500 145
[25/Nov/2024 11:21:14] "GET /main/cargo-vessel/ HTTP/1.1" 500 145
[25/Nov/2024 11:21:14] "GET /main/combined/ HTTP/1.1" 500 145

I am deeply thankful for your support and kindness

**Comment by esahin99** [comment]
Dear sduzs,

There are no PostgreSQL tables files in my code, the code already accessing the Postgres tables via the backend. Regarding the second question, you may have to install react-dom or other dependencies. I installed lots of dependencies when I was working on this project. I don't remember those libraries or dependencies right now sorry for that.

Best Regards

**Comment by 25zs25** [comment]
Dear esahin99:
Thank you for your detailed explanations. I've already resolved the "Invalid hook call" issue. What I meant was whether you read the information of tables like public."TransponderPing" during the database initialization. I didn't find the "create table" operations in the backend code.
The following are the problems currently encountered on the front end:
"Cannot read properties of null (reading 'labels')"
"TypeError: Cannot read properties of null (reading 'labels')"
The responses from the backend are:
"[26/Nov/2024 09:38:41] 'GET /main/trend-line/ HTTP/1.1' 500 145"
"[26/Nov/2024 09:38:41] 'GET /main/transponder-pings/?start_date=2035-02-01&end_date=2035-03-01 HTTP/1.1' 500 145"
Best Regards

**Comment by esahin99** [comment]
Dear sduzs,

I just uploaded the zip version of the code that I attended with the Vast Challenge 2024 for MC2 to google drive ([link](https://drive.google.com/drive/folders/1zVGOUa1bPLJ8UDdsXXgP_00FGhVP5_bx?usp=sharing)). If even this one still doesn't work, then most probably the source of the problem must related to other things.

Best Regards

**Comment by 25zs25** [comment]
Thank you very much for all your help. With my highest respects.

**Comment by 25zs25** [comment]
Dear esahin99:
I'm very sorry to disturb you again, but I still want to ask if you haven't processed the part related to the database. I haven't been able to find the code related to generating the Delivery_Report. The error message is: django.db.utils.ProgrammingError: relation "public.Delivery_Report" does not exist. 
Thank you for your response despite your busy schedule.

**Comment by esahin99** [comment]
Dear sduzs,

I haven't encountered this error before, so I don't know how to solve it. Sorry
